<a href="https://colab.research.google.com/github/25lahari/FMML_Projects_and_Labs/blob/main/Basics_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
mat1 = np.array([[1,2,3],[1,2,3]])
mat2 = np.array([[3,2,1],[3,2,1]])
print(mat1+mat2)

[[4 4 4]
 [4 4 4]]


In [4]:
mat1 = np.array([[1,2,3],[1,2,3]])
mat2 = np.array([[1,2],[1,2],[1,2]])
mat2 = mat2.reshape((2, 3))
print(mat1*mat2)

[[1 4 3]
 [2 2 6]]


In [5]:
mat1 = np.array([[1,2,3],[1,2,3]])
mat2 = np.array([[1,2],[1,2],[1,2]])

# Perform matrix multiplication using np.dot()
print(np.dot(mat1, mat2))

[[ 6 12]
 [ 6 12]]


In [8]:
a = [[1,2,3],[2,3,4],[4,2,4],[3,0,3]]
b = np.transpose(a)
print('a\n',a)
print('b\n',b)

a
 [[1, 2, 3], [2, 3, 4], [4, 2, 4], [3, 0, 3]]
b
 [[1 2 4 3]
 [2 3 2 0]
 [3 4 4 3]]


In [9]:
# Transpose of a Matrix (as NumPy array)
print ("Matrix and its Transpose")
a = np.array([[1,2,3],[2,3,4],[4,2,4],[3,0,3]])
b = a.T
print('a\n',a)
print('b\n',b)

Matrix and its Transpose
a
 [[1 2 3]
 [2 3 4]
 [4 2 4]
 [3 0 3]]
b
 [[1 2 4 3]
 [2 3 2 0]
 [3 4 4 3]]


In [10]:
 a = np.array([1,2,3])
 b = np.array([1,2,3])
 z = np.dot(a,b)
 print(z)

14


In [12]:
 a = [[1,2,3],[4,5,3],[0,-5,1]]
 b = [[-1,-2,5],[3,-6,4], [0,4,4]]
 z = np.dot(a,b)
 x = np.matmul(a,b)
 print(z)
 print(z==x)

[[  5  -2  25]
 [ 11 -26  52]
 [-15  34 -16]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [13]:
 newa = np.array(a)
 newb = np.array(b)
 y = newa.dot(newb)
 print(y)

[[  5  -2  25]
 [ 11 -26  52]
 [-15  34 -16]]


In [15]:
 a = np.random.randint(-4,4,(500,5))
 b = np.random.randint(-4,4,(5,1000))
 c = np.random.randint(-4,4,(1000,10))
 d = np.random.randint(-4,4,(10,2000))
 e = np.random.randint(-4,4,(2000,200))
 # Perform multiple matrix multiplication
 z = np.linalg.multi_dot([a,b,c,d,e])
 print(z)

[[-10320062  -7547457  -8714409 ...  -7786658 -11667844  -9075151]
 [ -2594394  -1674301  -1956350 ...  -1647883  -2123253  -2094788]
 [  2815716   1670286   2320992 ...   1373007   3394770   2764293]
 ...
 [ -5325962  -3311401  -4046128 ...  -3811089  -5825013  -5049206]
 [ -4596047  -3240350  -3852370 ...  -3288739  -5321326  -4145267]
 [ -9697386  -6470796  -7733538 ...  -6848060 -10521140  -8762388]]


In [16]:
%%time
z = np.linalg.multi_dot([a,b,c,d,e])
print(z, '\n')

[[-10320062  -7547457  -8714409 ...  -7786658 -11667844  -9075151]
 [ -2594394  -1674301  -1956350 ...  -1647883  -2123253  -2094788]
 [  2815716   1670286   2320992 ...   1373007   3394770   2764293]
 ...
 [ -5325962  -3311401  -4046128 ...  -3811089  -5825013  -5049206]
 [ -4596047  -3240350  -3852370 ...  -3288739  -5321326  -4145267]
 [ -9697386  -6470796  -7733538 ...  -6848060 -10521140  -8762388]] 

CPU times: user 11.3 ms, sys: 977 µs, total: 12.3 ms
Wall time: 11.9 ms


In [17]:
%%time
z = a.dot(b).dot(c).dot(d).dot(e)
print(z, '\n')


[[-10320062  -7547457  -8714409 ...  -7786658 -11667844  -9075151]
 [ -2594394  -1674301  -1956350 ...  -1647883  -2123253  -2094788]
 [  2815716   1670286   2320992 ...   1373007   3394770   2764293]
 ...
 [ -5325962  -3311401  -4046128 ...  -3811089  -5825013  -5049206]
 [ -4596047  -3240350  -3852370 ...  -3288739  -5321326  -4145267]
 [ -9697386  -6470796  -7733538 ...  -6848060 -10521140  -8762388]] 

CPU times: user 309 ms, sys: 6.1 ms, total: 315 ms
Wall time: 317 ms


In [18]:
a = np.array([[1,-2,3], [4,-1,0]])
b = np.array([6,3,2])
z = np.inner(a,b)
print(z)

[18 21]


In [19]:
a.dot(b.T)

array([18, 21])

In [20]:
 a = np.array([1,2,3,4,5])
 b = np.array([7,3,9])
 z = np.outer(a,b)
 print(z)

[[ 7  3  9]
 [14  6 18]
 [21  9 27]
 [28 12 36]
 [35 15 45]]


In [22]:
 # Here, 'a' matrix is 3D, which means there are 3 matrices each of 2x5 size
 # Similarly, for 'b' matrix
 # So we perform 3 matrix multiplication operations each with 2x5 and 5x3 matrices from a and b
 a = np.random.random([5,2,4])
 b = np.random.random([5,4,5])
 z = a @ b
 print(z.shape)

(5, 2, 5)


In [23]:
 a = np.random.randint(1,26,[5,5])
 det = np.linalg.det(a)
 print(int(det))

-377801
